//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01103	126.00	Exam &amp; Diag., Clinical Oral Permanent Dentition
        ///01202	37.10	Exam &amp; Diag., Limited Oral Previous Patient (recall)
        ///01204	48.90	Exam &amp; Diag., Limited Oral Specific
        ///01205	71.20	Exam &amp; Diag., Limited Oral Emergency
        ///02111	22.50	Radiographs, Intraoral Periapical-1 image
        ///02112	30.80	Radiographs, Intraoral Periapical-2 images
        ///02113	39.30	Radiographs, Intraoral Periapical-3 images
        ///02114	47.70	Radiographs, Intraoral Periapical-4 images
        ///02115	56.30	Radiographs, Intraoral Periapical-5 images
        ///02116	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BC_BCDA_2018_GPOOC {
            get {
                return ResourceManager.GetString("BC_BCDA_2018_GPOOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00011	Exam &amp; Diag.,Clinical Oral Dental Visit/Orientation	3	0	0	0	0	Diagnostic	/X/	EDCODV
        ///01101	Exam &amp; Diag.,Clinical Oral Primary Dentition	3	0	0	0	0	Diagnostic	/X/	Primary Exam
        ///01102	Exam &amp; Diag.,Clinical Oral Mixed Dentition	3	0	0	0	0	Diagnostic	/X/	Mixed Exam
        ///01103	Exam &amp; Diag.,Clinical Oral Permanent Dentition	3	0	0	0	0	Diagnostic	/X/	Permanent Exam
        ///01201	Exam &amp; Diag.,Limited Oral New Patient	3	0	0	0	0	Diagnostic	/X/	Ex,NP, Ltd
        ///01202	Exam &amp; Diag.,Limited Oral Previous Patient (recall)	3	0	0	0	0	Diagno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string canadianprocedurecodes {
            get {
                return ResourceManager.GetString("canadianprocedurecodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///SQLyog Community- MySQL GUI v8.22 
        ///MySQL - 5.5.9 : Database - ehrfordump79
        ///*********************************************************************
        ///*/        ///
        ///
        ////*!40101 SET NAMES utf8 */;
        ///
        ////*!40101 SET SQL_MODE=&apos;&apos;*/;
        ///
        ////*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
        ////*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=&apos;NO_AUTO_VALUE_ON_ZERO&apos; */;
        ////*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
        ////*Table structure for table `account` */
        ///
        ///CREATE TABLE `account` (
        ///  `AccountNum` b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dump {
            get {
                return ResourceManager.GetString("dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00*          *00*          *30*330989922      *30*330989922      *171003*0802*U*00401*000000000*0*P*:~
        ///GS*HP*330989922*330989922*20171003*0802*0*X*004010X091A1~
        ///ST*835*0001~
        ///BPR*I*353*C*CHK************20171004~
        ///TRN*1*0045284538*1942761537~
        ///REF*EV*DDSRIX00~
        ///DTM*405*20171001~
        ///N1*PR*Delta Dental Insurance Co~
        ///N3*PO Box 1809~
        ///N4*Alpharetta*GA*30023~
        ///PER*CX*CUSTOMER SERVICE*TE*8005212651~
        ///N1*PE*Chirag R Vaid Dds Dental Corp*FI*123456789~
        ///N3*2201 Main Ave Ste 100~
        ///N4*Salem*OR*973055722~
        ///REF*TJ*811902608~
        ///LX*1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JustinSmithERA {
            get {
                return ResourceManager.GetString("JustinSmithERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00* *00* *30*330989922 *ZZ*810624427
        ///*190114*1300*U*00401*331188226*0*P*:~
        ///GS*HB*330989922*330989922*20190114*1300*331188226*X*004010X092A1~
        ///ST*271*0001~
        ///BHT*0022*11*331188226WEB*20190114*1300~
        ///HL*1**20*1~
        ///NM1*PR*2*METLIFE*****PI*65978~
        ///HL*2*1*21*1~
        ///NM1*1P*1*PROFESSIONAL DENTAL ALLIANCE OF GEO*****XX*1861900946~
        ///HL*3*2*22*1~
        ///NM1*IL*1*ABBOTT*NYKIA*R***MI*420231637~
        ///EB*F*IND*24***29*1874.00~
        ///EB*C*FAM*24**MET*32*60.00~
        ///EB*C*FAM*24**MET*22*0.00~
        ///EB*C*IND*24**MET*32*0.00~
        ///EB*C*IND*24**MET*22*0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string x271Test {
            get {
                return ResourceManager.GetString("x271Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA*00*          *00*          *ZZ*MB000667       *ZZ*D3-FCCCOA-ADC  *151209*0602*=*00501*001423769*0*P*&gt;~
        ///GS*BE*MB000000*D3-FCCCOA-ADC*20151209*0602*1326518*X*005010X220A1~
        ///ST*834*7786518*005010X220A1~
        ///BGN*00*7786518*20151209*0602****2~
        ///N1*P5*TestCarrierNew*FI*930878074~
        ///N1*IN*TestCarrierNew*FI*MBFE4345345083-Test~
        ///N1*TV*TESTTT*FI*11-11111~
        ///INS*Y*18*001*33*A~
        ///REF*0F*CG00000B~
        ///REF*1L*MBFE4345345083-Test~
        ///REF*23*CG00000B~
        ///DTP*356*D8*20140101~
        ///DTP*357*D8*20140122~
        ///NM1*IL*1*Patient*Testx834****34* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string x834Test {
            get {
                return ResourceManager.GetString("x834Test", resourceCulture);
            }
        }
    }
}
